/** USER ACTIONS **/
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER = 'SET_USER';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';

/** ERRORS ACTIONS **/
export const SET_ERROR  = 'SET_ERROR';
export const RESET_ERRORS = 'RESET_ERRORS';

/** ERROR KEYS **/
export const LOGIN_ERROR_KEY = 'LOGIN_ERROR_KEY';
export const REGISTER_ERROR_KEY = 'REGISTER_ERROR_KEY';